### ISSUE TITLE
[EPIC] Directorio

### ISSUE THREAD

**Issue by javatlacati** [javatlacati/temachpedia#4]
Como nuevo miembro de la comunidad quisiera saber cuáles son las cuentas oficiales para:

- [x] unirme a los compas de hierro más cercanos
- [ ] oír las canciones que salen en los lives
- [ ] saber que días está el Temach en vivo en cada red social
- [ ] saber los eventos de la semana y a que comunidad contacto
- [ ] saber en que podcast ha participado el temach
