### ISSUE TITLE
[EPIC] Biblioteca de los compas

### ISSUE THREAD

**Issue by javatlacati** [javatlacati/temachpedia#83]
**¿Su sugerencia está relacionada con un problema? Por favor describa.**
Como compa lector me gustaría acceder a la biblioteca de los compas de una manera más organizada a la actual ya que pocos de los compas saben realmente de su existencia. Obviamente para esta característica se necesitaría haber iniciado sesión

**Describe la solución que te gustaría**

- [ ] Búsqueda por título de los libros
- [ ] Búsqueda por autor de los libros
- [ ] Que al dar click me abra libro para descargar de su ubicación actual si tengo permiso, si no que me permita solicitarlo

**Describe las alternativas que hayas considerado**
También se podría incluir la biblioteca de las omegas y otras bibliotecas de recursos en internet

**Contexto adicional**
Los compas Bibliotecarios se encargan de la biblioteca de los compas, ellos necesitarían un rol especial y permisos en el sistema.
